[project]
name = "ingest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "h3>=4.4.2",
    "pandas>=3.0.0",
    "pydantic>=2.12.5",
    "requests>=2.32.5",
]
